### ISSUE TITLE
MegaM@Rt integration: no installation instructions available in readme.md

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [veriatl/VeriATL#3]
Hi,
In order to integrate VeriATL tool within the MegaM@Rt toolset I need installation instructions that I can't see in the readme.md:
- Do you have an update site to install the plugins?
- What plugins should be installed?
- I don't see any feature project in the code base, could you create one that encloses all required plugins
- Could you update your software to be compatible with Eclipse 2018-09 modeling version?
Please, provide me your answers asap. Thank you very much in advance.
Yosu

**Comment by veriatl** [comment]
Hi @jesus-gorronogoitia

> I need installation instructions that I can't see in the readme.md

addressed in #5

> Do you have an update site to install the plugins?

addressed in #4 

> What plugins should be installed?

please refer updated readme.md

>I don't see any feature project in the code base, could you create one that encloses all required plugins

addressed in #6 

> Could you update your software to be compatible with Eclipse 2018-09 modeling version?

Updated, which partially works on my side, and ongoing development to make it fully compatible with Eclipse 2018-09.

Thank you.
Zheng

**Comment by jesus-gorronogoitia** [comment]
Hi @veriatl Thank you so much, I will take care of testing your improvements for installation asap

**Comment by jesus-gorronogoitia** [comment]
Hi @veriatl , thanks, I could install VeriATL in Eclipse Modeling 2018-09.
